# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29a743f04ae4d1cdbc49045d1fa8752a89a6d1d65b2cbc0a9d3a5ae9edfb425cf1094a614888b0cdebe719b75b2dfe26ae5ca099e452f544f272cd6e711d9049

test:
  secret_key_base: 7b0195744fb830941740a224a5147169b52e024656046a6f4c43c63f235f5ec95a7ee5f9dc40585c569d89b7c2dfa5393cfc2fd040da11bcc6360a481def4d8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
